TEST ADO MVC/Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TEST_ADO_MVC.Models
{
    public class Employee : Timesheets
    {
        [Key]
        public int id { get; set; }
        [Required]
        public string last_name { get; set; }
        [Required]
        public string first_name { get; set; }
    }
}

TEST ADO MVC/Models/ErrorViewModel.cs
namespace TEST_ADO_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TEST ADO MVC/Models/Timesheets.cs
using System.ComponentModel.DataAnnotations;

namespace TEST_ADO_MVC.Models
{
    //Основная модель записей об отсутствии. Поля как в БД.
    public class Timesheets
    {
        [Key]
        public int id { get; set; }
        [Required]
        public int employee { get; set; }
        [Required]
        public int reason { get; set; }
        [Required]
        public DateTime start_date { get; set; }
        [Required]
        public int duration { get; set; }
        [Required]
        public bool discounted { get; set; }
        [Required]
        public string description { get; set; }
        [Required]
        public string name_employee { get; set; }
        [Required]
        public List<Employee> employees { get; set;}
    }
}

TEST ADO MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TEST_ADO_MVC.Models;

namespace TEST_ADO_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TEST ADO MVC/Controllers/TimesheetsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TEST_ADO_MVC.DAL;
using TEST_ADO_MVC.Models;

namespace TEST_ADO_MVC.Controllers
{
    public class TimesheetsController : Controller
    {
        private readonly Timesheets_DAL _dal;
        public TimesheetsController(Timesheets_DAL dal)//Ссылка на слой данных БД.
        {
            _dal= dal;
        }

        [HttpGet]
        public IActionResult Index()//Основная страница с данными.
        {
            List<Timesheets> timesheets = new List<Timesheets>();
            try
            {
                timesheets = _dal.GetAll();//Вызывается метод, который заполняет таблицу на форме из БД.

            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
            }


            return View(timesheets);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Timesheets model)//Страница добавления данных в таблицу и БД.
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["errorMessage"] = "Model data is invalid";
                }
                bool result = _dal.Insert(model);//Вызывается метод, который добавляет данные на форму и БД.

                if (!result)
                {
                    TempData["errorMessage"] = "Unable to save data";
                    return View();
                }
                TempData["successMessage"] = "Данные сохранены";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
            
        }
        [HttpGet]
        public IActionResult Edit(int id)//Получение строки для изменения при нажатии кнопки Edit или переадресации по ссылке.
        {
            try
            {
                Timesheets timesheets = _dal.GetbyId(id);
                if (timesheets.id == 0)
                {
                    TempData["errorMessage"] = $"Запись с идентификатором ({id}) не найдена.";
                    return RedirectToAction("Index");
                }
                return View(timesheets);
            }
            catch(Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(Timesheets model)//Основной метод изменения данных в выбранной строке.
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["errorMessage"] = "Model data is invalid";
                }
                bool result = _dal.Update(model);//Вызывается метод из DAL, который обновляет данные в форме и базе.

                if (!result)
                {
                    TempData["errorMessage"] = "Unable to save data";
                    return View();
                }
                TempData["successMessage"] = "Данные сохранены";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)//Метод для получения строки для удаления.
        {
            try
            {
                Timesheets timesheets = _dal.GetbyId(id);
                if (timesheets.id == 0)
                {
                    TempData["errorMessage"] = $"Запись с идентификатором ({id}) не найдена.";
                    return RedirectToAction("Index");
                }
                return View(timesheets);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Delete_Conf(Timesheets model)//Метод для формы удаления строки данных из таблицы и базы.
        {
            try
            {
                bool result = _dal.Delete(model.id);

                if (!result)
                {
                    TempData["errorMessage"] = "Unable to delete data";
                    return View();
                }
                TempData["successMessage"] = "Данные удалены";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
    }
}

TEST ADO MVC/Views/Home/Index.cshtml
@model List<TEST_ADO_MVC.Models.Timesheets>

@{
    ViewData["Title"] = "Начальная страница";
    var errorMessage = TempData["errorMessage"]?.ToString();
}
<h3>@ViewData["Title"]</h3>
<hr />

TEST ADO MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TEST_ADO_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TEST_ADO_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TEST_ADO_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="timesheets" asp-action="">Timesheets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TEST_ADO_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TEST ADO MVC/Views/Timesheets/Create.cshtml
@model TEST_ADO_MVC.Models.Timesheets

@{
    ViewData["Title"] = "Создать запись";
    var errorMessage = TempData["errorMessage"]?.ToString();
}
<h3>@ViewData["Title"]?.ToString()</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(errorMessage))
{
        <div class="alert alert-danger">
            <b>Error : </b>@errorMessage
            <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
}
<form action="Create" method="post" class="mt-3" autocomplete="off">
    <div class="mb-3">
        <label class="form-label">Идентификатор</label>
        <input type="text" class="form-control" asp-for="id" />
        <span asp-validation-for="id" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Сотрудник</label>
        <input type="text" class="form-control" asp-for="employee" />
        <span asp-validation-for="employee" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Причина отсутствия</label>
        <select asp-for="reason">
            
                
@*                @foreach (var employee in Model.employees)
                {
                    <option selected="selected" value="@employee.id">@employee.last_name @employee.first_name</option>
                }*@
            
            <option selected="selected" disabled="disabled">Выберите причину </option>
            <option selected="selected" value="1">Отпуск</option>
            <option selected="selected" value="2">Больничный</option>
            <option selected="selected" value="3">Прогул</option>
        </select>
        <span asp-validation-for="reason" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Дата начала</label>
        <input type="date" class="form-control" asp-for="start_date" />
        <span asp-validation-for="start_date" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Продолжительность(раб.дней)</label>
        <input type="text" class="form-control" asp-for="duration" />
        <span asp-validation-for="duration" class="text-danger"></span>
    </div>
    <div class="mb-1">
        <label class="form-label">Учтено при оплате</label>
        <input type="checkbox" asp-for="discounted" />
        <span asp-validation-for="discounted" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Комментарий</label>
        <input type="text" class="form-control" asp-for="description" />
        <span asp-validation-for="description" class="text-danger"></span>
    </div>
    <div class="d-grid">
        <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TEST ADO MVC/Views/Timesheets/Delete.cshtml
@model TEST_ADO_MVC.Models.Timesheets

@{
    ViewData["Title"] = "Удалить запись";
    var errorMessage = TempData["errorMessage"]?.ToString();
}
<h3>ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(errorMessage))
{
    <div class="alert alert-danger">
        <b>Error : </b>@errorMessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<form action="Delete" method="post">
    <div class="mb-3">
        <label class="form-label">Идентификатор</label>
        <input type="text" class="form-control" asp-for="id" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Сотрудник</label>
        <input type="text" class="form-control" asp-for="employee" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Причина отсутствия</label>
        <input type="text" class="form-control" asp-for="reason" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Дата начала</label>
        <input type="date" class="form-control" asp-for="start_date" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Продолжительность(раб.дней)</label>
        <input type="text" class="form-control" asp-for="duration" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Учтено при оплате</label>
        <input type="text" class="form-control" asp-for="discounted" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Комментарий</label>
        <input type="text" class="form-control" asp-for="description" readonly />
    </div>
    <div class="d-grid">
        <button type="submit" class="btn btn-danger">Удалить</button>
    </div>
</form>

TEST ADO MVC/Views/Timesheets/Edit.cshtml
@model TEST_ADO_MVC.Models.Timesheets

@{
    ViewData["Title"] = "Изменить запись";
    var errorMessage = TempData["errorMessage"]?.ToString();
}
<h3>ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(errorMessage))
{
            <div class="alert alert-danger">
                <b>Error : </b>@errorMessage
                <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
}
<form action="Edit" method="post">
    <div class="mb-3">
        <label class="form-label">Идентификатор</label>
        <input type="text" class="form-control" asp-for="id" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Сотрудник</label>
        <input type="text" class="form-control" asp-for="employee" />
        <span asp-validation-for="employee" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Причина отсутствия</label>
        <input type="text" class="form-control" asp-for="reason" />
        <span asp-validation-for="reason" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Дата начала</label>
        <input type="date" class="form-control" asp-for="start_date" />
        <span asp-validation-for="start_date" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Продолжительность(раб.дней)</label>
        <input type="text" class="form-control" asp-for="duration" />
        <span asp-validation-for="duration" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Учтено при оплате</label>
        <input type="text" class="form-control" asp-for="discounted" />
        <input type="checkbox" class="form-control" asp-for="discounted" />
        <span asp-validation-for="discounted" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Комментарий</label>
        <input type="text" class="form-control" asp-for="description" />
        <span asp-validation-for="description" class="text-danger"></span>
    </div>
    <div class="d-grid">
        <button type="submit" class="btn btn-success">Изменить</button>
    </div>
</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TEST ADO MVC/Views/Timesheets/Index.cshtml
@model List<TEST_ADO_MVC.Models.Timesheets>

@{
    ViewData["Title"] = "Записи об отсутствии";
    var errorMessage = TempData["errorMessage"]?.ToString();
    var successMessage = TempData["successMessage"]?.ToString();
}
<h3>@ViewData["Title"]?.ToString()</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(@successMessage))
{
    <div class="alert alert-success">
        <b>Success : </b>@successMessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else if (!string.IsNullOrWhiteSpace(errorMessage))
{
    <div class="alert alert-danger">
        <b>Error : </b>@errorMessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<form>
    <button asp-action="Create" asp-controller="Timesheets" class="btn btn-primary">Создать запись</button>
    <table class="table table-responsive table-hover">
        <thead>
            <tr class="table-active">
                <th>Идентификатор</th>
                <th>Сотрудник</th>
                <th>Причина отсутствия</th>
                <th>Дата начала</th>
                <th>Продолжительность(раб.дней)</th>
                <th>Учтено при оплате</th>
                <th>Комментарий</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (var timesheets in Model)
                {
                    <tr>
                        <td>@timesheets.id</td>
                        <td>@timesheets.name_employee (@timesheets.employee)</td>
                        <td>@timesheets.reason</td>
                        <td>@timesheets.start_date.ToString()</td>
                        <td>@timesheets.duration</td>
                        <td>@timesheets.discounted</td>
                        <td>@timesheets.description</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a asp-controller="Timesheets" asp-action="Edit" asp-route-id="@timesheets.id" class="btn
                                btn-primary">Edit</a>
                                <a asp-controller="Timesheets" asp-action="Delete" asp-route-id="@timesheets.id" class="btn
                                btn-danger">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="8">
                        <div>
                            Нет ни одной записи!
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>